  name: build

  on: push

  jobs:
    build:
      name: rust-build
      runs-on: ${{matrix.os}}
      strategy:
        matrix:
          include:
            - build: linux  # build job for x86_64 Linux
              os: ubuntu-latest
              rust: stable
              target: x86_64-unknown-linux-gnu
              cross: false
            - build: macos
              os: macos-latest  # build job for x86_64 macOS
              rust: stable
              target: x86_64-apple-darwin
              cross: false
            - build: windows
              os: windows-latest  # build job for x86_64 macOS
              rust: stable
              target: x86_64-pc-windows-gnu
              cross: false
            - build: arm-v7  # build job for arm Linux
              os: ubuntu-latest
              rust: stable
              target: armv7-unknown-linux-gnueabihf
              linker: gcc-arm-linux-gnueabihf
              cross: true
            - build: aarch64  # build job for arm64 Linux
              os: ubuntu-latest
              rust: stable
              target: aarch64-unknown-linux-gnu
              linker: gcc-aarch64-linux-gnu
              cross: true
            - build: aarch64  # build job for arm64 macOS
              os: macos-latest
              rust: stable
              target: aarch64-apple-darwin
              cross: false
      steps:
      - name: Install Linker
        if: matrix.cross
        run: |
          sudo apt update
          sudo apt install ${{ matrix.linker }}
      - name: Install Rust
        run: |
          ls -a
          pwd
          rustup install ${{ matrix.rust }}
          rustup target add ${{ matrix.target }}
          rustup show
          ls -a
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
