on: [push]

name: x86_64-apple-darwin

jobs:
  aarch64-linux:
    name: x86_64-apple-darwin
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-apple-darwin --release
      - uses: actions/upload-artifact@v3
        with:
          name: x86_64-apple-darwin
          path: ./target/x86_64-apple-darwin/release/minigrep